name: Release Integration

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string
      releases:
        required: true
        type: string

jobs:
  check-registry:
    name: Check Registry
    {{> partialsJobIf }}
    {{> partialsJobDefaults }}
    steps:
      - name: View in Registry
        run: echo "all good!"
